/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _hw_1;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean search_three(ArrayList<Integer> array, Integer a, Integer b ,Integer c ){
            if (array==null) return false;

            boolean founda,foundb,foundc;
            founda=false;
            foundb=false;
            foundc=false;

            for (Integer element : array) {
                if (element == a) founda=true;
                if (element == b) foundb=true;
                if (element == c) foundc=true;
            }

            return founda & foundb & foundc;

    }
}
